
def country_acronym_to_flag(acronym):
    # Mapping of non-standard acronyms to standard ones
    mapping = {
        "CHN": "CN",
        "KOR": "KR",
        "GBR": "GB",
        "USA": "US",
        "SUI": "CH",
        "ESP": "ES",
        "GER": "DE",
        "NED": "NL",
        "NZL": "NZ",
        "RUS": "RU",
        "SRB": "RS",
        "MEX": "MX",
        "NOR": "NO",
        "DEN": "DK",
        "FIN": "FI",
        "ARG": "AR",
        "COL": "CO",
        "TUR": "TR",
        "POR": "PT",
        "CZE": "CZ",
        "AUT": "AT",
        "GRE": "GR",
        "BEL": "BE",
        "IRN": "IR",
        "IRL": "IE",
        "EGY": "EG",
        "SAF": "ZA",
        "VIE": "VN",
        "THA": "TH",
        "POL": "PL",
        "SWE": "SE",
        "HUN": "HU",
        "BRA": "BR",
        "CAN": "CA",
        "JPN": "JP",
        "ITA": "IT",
        "FRA": "FR",
        "AUS": "AU",
        "ROU": "RO",
        "ISR": "IL",
        "HKG": "HK",
        "GEO": "GE",
        "UKR": "UA",
        "CRO": "HR",
        "PHI": "PH",
        "UZB": "UZ",
    }
    # Convert the acronym using the mapping dictionary
    standard_acronym = mapping.get(acronym, acronym)
    return ''.join(chr(ord(char) + 127397) for char in standard_acronym.upper())
